apiVersion: apps/v1
kind: Deployment
metadata:
  name: ott-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ott-frontend
  template:
    metadata:
      labels:
        app: ott-frontend
    spec:
      containers:
      - name: frontend
        image: imi1998/ott-frontend:v1
        ports:
        - containerPort: 3000

